# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xander's blog
email: xander@smeets.onl
description: > # this means to ignore newlines until "baseurl:"
  I will write some things I am interested in on this site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://x.smeets.onl" # the base hostname & protocol for your site
twitter_username: XSmeets
github_username:  XSmeets

# Build settings
markdown: kramdown
